### ISSUE TITLE
Race condition when writing crc32c.dll to disk in NativeProxy

### ISSUE THREAD

**Issue by omar** [robertvazan/crc32c.net#5]
We're seeing an issue where when two threads attempt to use the NativeProxy indirectly (in our use case, through Snappy.NET's SnappyStream), an error is thrown when both threads attempt to copy the crc32c.dll to disk from the embedded resource.

The code in question is https://github.com/robertvazan/crc32c.net/blob/master/Crc32C.NET/NativeProxy.cs#L30

Is there a way to have crc32c.dll shipped with the package instead of as an embedded resource to remove this issue?

**Comment by omar** [comment]
Relevant stack trace:

```
System.TypeInitializationException: The type initializer for 'Crc32C.NativeProxy' threw an exception. ---> System.IO.IOException: The process cannot access the file 'C:\Users\{USERNAME}\AppData\Local\Temp\Crc32C.NET-2.0.225.3\crc32c64.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Crc32C.NativeProxy..ctor(String name)
   at Crc32C.NativeProxy..cctor()
   --- End of inner exception stack trace ---
   at Crc32C.Crc32CAlgorithm.AppendInternal(UInt32 initial, Byte[] input, Int32 offset, Int32 length)
   at Snappy.SnappyFrame.ComputeMasked(Byte[] data, Int32 offset, Int32 count)
   at Snappy.SnappyFrame.GetData(Byte[] buffer, Int32 offset)
   at Snappy.SnappyStream.EnsureAvailable()
   at Snappy.SnappyStream.Read(Byte[] buffer, Int32 offset, Int32 count)
```

**Comment by robertvazan** [comment]
A temporary workaround is to force initialization early in program execution or to synchronize on application level. I am busy at the moment, so this will remain open for some time.

**Comment by robertvazan** [comment]
This library is no longer maintained. Feed free to adopt it if you find it useful.
